In [1]:
#Setup
%matplotlib inline
%config IPCompleter.greedy=True
import datetime as dt
import pytz
import time
import os
import psycopg2
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
from pythonLib.helper import *
import sklearn.preprocessing as skp
import sqlalchemy
# fix random seed for reproducibility
# seed = 7
DATA_DIR = 'data' 
# np.random.seed(seed)
dbString = 'postgresql://s2c:JANver95@localhost:5432/stockdata'
curInstList = 'tradeList.txt'
engine = sqlalchemy.create_engine(dbString) 

from keras.models import Sequential,Model
from keras.layers import Activation,Dense,LSTM, Dropout,Conv1D,MaxPooling1D,Permute,Merge,Input
from keras.layers import Flatten,BatchNormalization,LeakyReLU,GlobalAveragePooling1D,concatenate
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from keras.losses import binary_crossentropy
from keras.optimizers import SGD,Adam
from keras.models import load_model
from pythonLib.layer_utils import AttentionLSTM
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
import h5py

from sklearn.utils import class_weight
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

import tensorflow as tf
import tempfile
tf.__version__

import backtrader as bt
import datetime as dt
import pytz
import math
import backtrader.plot as pLaut


/home/s2c/anaconda3/envs/AlgoTrading/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/s2c/anaconda3/envs/AlgoTrading/lib/python3.6/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [2]:
stockList = []
with open (curInstList) as f:
    for each_csv in f:
        each_csv = each_csv.rstrip('\n') # read csv
        curTicker = each_csv # store ticker
        stockList.append(curTicker)
cur = 0


In [3]:
query = "SELECT * FROM histdata WHERE ticker = '%s' ORDER BY datetime ASC" % stockList[cur]
dat = pd.read_sql(query,engine)
utc = pytz.UTC
startDate = utc.localize(dt.datetime(2014,3,8))
endDate = utc.localize(dt.datetime(2017,12,30))
backTestStart = endDate
backTestEnd = endDate + dt.timedelta(days=7*4*10)
res = dat[(dat['datetime'] > startDate) & (dat['datetime'] < endDate)]


In [5]:
# # Setup Parameters
dataInit = res # Read the stock price data. This is 1 minute data
data = dataInit['close'] # extract the 'close' column as a Pandas series
# plt.figure()
# pd.tools.plotting.lag_plot(data) # Lag plot to check randomness
# plt.figure()
# pd.tools.plotting.autocorrelation_plot(data) # Auto correlation plot to check if series is autocorrelated at all

# # Find the right lag manually
# targetCorr = 0.99 # autocorrelation we want
# lag = findLag(data,targetCorr,True) # Lag that is indicative 
# if lag == 99: #if lag is 99 then we can just use any number above it as autocorrelation is guaranteed.
#     lag = 120 #nice round 2  hour intervals
# print(lag)
lag = 60
lookahead = 20
flat = 1.5
series = timeseriesLagged(data,lag + lookahead-1) # Generate the lagged series
# res.tail(10)
labs = range(lag+1,lag+lookahead+1)
labs = [str(i) for i in labs]

In [6]:
seriesLabs = series[labs] # labels
seriesFeats = series.drop(labs,axis=1) #features
seriesFeats = seriesFeats.values
seriesLabs = seriesLabs.values

In [7]:
mean = np.mean(seriesFeats,axis=1,keepdims=True)
std = np.std(seriesFeats,axis=1,keepdims=True)

In [8]:
seriesFeatsSubbed = seriesFeats - mean
seriesFeatsNormed = seriesFeatsSubbed/std 
seriesLabsSubbed = seriesLabs - mean
seriesLabsNormed = seriesLabsSubbed/std

In [28]:
# x,y,Mean,Std = shuffle(seriesFeatsNormed,seriesLabsNormed,mean,std)
x,y,Mean,Std = seriesFeatsNormed,seriesLabsNormed,mean,std
x = x.reshape(-1,lag,1)
y = y.reshape(-1,lookahead)
tot = len(x)
y = y
trainPercent = 0.7 # majority of data used for training
testPercent = 0.95 # 
valPercent = 1.00  #

# Test Train Val Split

xTrain = x[0:int(trainPercent*tot),:,:]
yTrain = y[0:int(trainPercent*tot)]
trainMean = Mean[0:int(trainPercent*tot),:]
trainStd = Std[0:int(trainPercent*tot),:]

xTest = x[int(trainPercent*tot): int(testPercent*tot),:,:]
yTest = y[int(trainPercent*tot): int(testPercent*tot)]
testMean = Mean[int(trainPercent*tot): int(testPercent*tot),:]
testStd = Std[int(trainPercent*tot): int(testPercent*tot),:]

xVal = x[int(testPercent*tot):,:]
yVal = y[int(testPercent*tot):]
valMean = Mean[int(testPercent*tot):]
valStd = Std[int(testPercent*tot):]

In [10]:
assert xTrain.shape[0] == yTrain.shape[0]
assert xTest.shape[0] == yTest.shape[0]
assert xVal.shape[0] == yVal.shape[0]

learnRate = 0.05
batchSize = 100
totalBatches = (xTrain.shape[0]//batchSize)
epochs = 5

nClasses = 2
nLength = xTrain.shape[1]
inputShape = (nLength,1)
# xTrainDataSet = tf.data.Dataset.from_tensors(xTrain)
# xTrainIter = xTrainDataSet.make_one_shot_iterator()

In [14]:
# inputs = Input(shape=inputShape)

# LSTM1 = LSTM(45,
#         activation="tanh",name="LSTM1")(inputs)
# FCN1 = Dense(20,activation='relu',name="FCN1")(LSTM1)
# FCN2 = Dense(10,activation='relu',name="FCN2")(FCN1)
# Preds = Dense(1,activation='linear',name="Linear")(FCN2)


In [134]:
# Keras
#https://arxiv.org/pdf/1709.05206.pdf LSTM-FCN
def buyConvModel():
    buyModelConv = Sequential()
    buyModelConv.add(Conv1D(112, 
                            kernel_size= 2, 
                            strides=1, 
                            input_shape=inputShape,
                            batch_size = None,
#                            kernel_regularizer=regularizers.l1(0.01)
                           )              
                     )
    buyModelConv.add(BatchNormalization())
    buyModelConv.add(Activation('relu'))
#     buyModelConv.add(Dropout(0.8))
    
    
    buyModelConv.add(Conv1D(256, kernel_size= 4, strides=1,
#                             kernel_regularizer=regularizers.l1(0.01)
                           ))
    buyModelConv.add(BatchNormalization())
    buyModelConv.add(Activation('relu'))


    buyModelConv.add(Conv1D(384, kernel_size= 4, strides=1))
     buyModelConv.add(Activation('relu'))
    buyModelConv.add(Conv1D(384, kernel_size= 4, strides=1))
     buyModelConv.add(Activation('relu'))
    buyModelConv.add(Conv1D(256, kernel_size= 4, strides=1))
    buyModelConv.add(Activation('relu'))

    im = buyModelConv.layers[0].input
    buyConvInput = buyModelConv(im)

    return [buyConvInput,im]
l = buyConvModel()
output = Dense(20, activation='relu')(l[0])
# output1 = Dense(20, activation='relu')(output)
# output2 = Dense(20, activation='linear')(output1)
buyModel = Model(inputs=l[1],outputs=output)

In [135]:
# model = Model(inputs=inputs, outputs=Preds)
buyModel.compile(loss="mean_squared_error",
              optimizer=Adam(lr=learnRate),
              metrics=['mse']
             )

buyModel.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_157_input (InputLayer (None, 60, 1)             0         
_________________________________________________________________
sequential_48 (Sequential)   (None, 47, 256)           1494032   
Total params: 1,494,032
Trainable params: 1,493,296
Non-trainable params: 736
_________________________________________________________________


In [136]:
buyModel.fit(x=xTrain,
             y=yTrain, 
#              class_weight=classWeight,
             validation_data = (xVal,yVal),
             batch_size = batchSize,
             epochs = 5 )

ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[-2.26931294, -1.32113205, -1.41595014, ..., -3.21749384,
        -3.21749384, -3.21749384],
       [-1.22973126, -1.32082246, -2.1406433 , ..., -3.05155535,
        -3.05155535, -3.05155535],...

In [127]:
yPreds = model.predict(xTest)

In [60]:
yTested = (yTest*testStd) +testMean
yTested[:,-1]

array([503.6 , 503.6 , 503.55, ..., 535.95, 537.7 , 538.  ])

In [61]:
yPredFin = (yPreds * testStd) + testMean
yPredFin[:,-1]

array([503.29414521, 503.61998976, 503.52789347, ..., 539.63304938,
       539.58929365, 539.62036137])

In [62]:
xFin = xTest.reshape(-1,lag) * testStd + testMean
xFin = xFin[:,-1].reshape(-1,1)

In [63]:
resAct = yTested[:,-1].reshape((-1,1))-xFin

In [64]:
resPred = yPredFin[:,-1].reshape(-1,1) - xFin

In [65]:
resActBinned = np.where(resAct<=0,-1,1)
resPredBinned = np.where(resPred<=0,-1,1)

In [66]:
resActBinned

array([[ 1],
       [-1],
       [-1],
       ...,
       [-1],
       [-1],
       [-1]])

In [67]:
confusion_matrix(resActBinned,resPredBinned)

array([[32620,  2848],
       [30466,  3453]])